Mobile version
aster-alemu/Mobile-Version pull request #1
Opened 2022-04-22 20:19 UTC by aster-alemu

In this PR I have been doing the following activities

1. Create remote repository
2. Clone remote repository on to my local machine using git clone command followed by the SSH link
3. Set up GitHub action and Linters on my local environment
4. Create branch repository using the command git branch followed by the name of the new branch
5. Switch from main branch to newly created branch using the command git checkout followed by the name of newly created branch
6. Create html file with name index.html
7. Create css file with name style.css
8. Edit the README.md file
9. Check for stylelint error
10. Add, commit and push the file into Mobile version branch

2022-04-22 23:22 UTC, zieeco requested changes
Hi @aster-alemu 

<img src="https://media4.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Nice design
- Descriptive PR
- No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 23:22 UTC, zieeco commented on index.html
> +  <div class="works">
- [ ] Please, kindly use a `<section tag>` instead of `<div>` tag here.

2022-04-22 23:22 UTC, zieeco commented on style.css
> +}
- [ ] Please, kindly use the right `font-family` on your `Multi-Post stories`
- [ ] Add `margin-top, margin-bottom`  to your `paragraph` and `header` 
- [ ] Align, your `see-project-button` and `list items buttons` to match the design. This happened as a result of the padding you add to the `li` in your `style.css` line `80` 

```
li {
  display: inline;
  list-style: none;
  padding: 12px;
}
```
> || **YOUR DESIGN** || **FIGMA DESIGN** ||
> |-|---------|-|---------|-|
> || ![section](https://user-images.githubusercontent.com/59397159/164813854-ef2e6ecd-c22c-4d2d-983c-0c2a18801919.png)  ||  ![section2](https://user-images.githubusercontent.com/59397159/164813877-aca9eba0-4c95-4f29-8c5f-3c928da556de.png) ||

2022-04-22 23:22 UTC, zieeco commented on style.css
> +}
- [ ] Kindly, use the color, font family,  and font-weight from the Figma design for your `My Recent Work`

2022-04-22 23:22 UTC, zieeco commented on style.css
> +}
- [ ]  Kindly, use the font family from the Figma design

2022-04-22 23:22 UTC, zieeco commented on style.css
> +}
- [ ] Please, kindly add the `icons` to your `headings`

![3](https://user-images.githubusercontent.com/59397159/164816413-34bd32b7-b3dc-47df-8be0-391f4fe58b90.png)
![2](https://user-images.githubusercontent.com/59397159/164816415-e334fc7c-4779-4f06-83db-d297ea22d4fe.png)
![one](https://user-images.githubusercontent.com/59397159/164816416-d6cbffaa-47fe-4612-ad87-3043626e3817.png)

2022-04-23 08:50 UTC, Deepakdanger approved these changes
Hi @aster-alemu, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] [optional] The button (e.g., "See project, Get my resume, submit") is a link a or button tag, and follow the button styling: Active, Hover, and Pressed (see design), Kindly add this before further project building.
- 
![Screenshot from 2022-04-23 14-17-17](https://user-images.githubusercontent.com/26767383/164887548-90a0b080-5298-4763-b9a0-d537273af79e.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 08:56 UTC, Deepakdanger commented
I mistakenly, select approve here, but you can ask for review after completing the required changes.

**Don't merge now, Ask for a review after doing changes**

2022-04-23 14:28 UTC, roshan-bajgain approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/lFHtqqh6orvAhbiGmy/giphy.gif"/>

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 

## Optional Suggestion

- [ ] This is your last review So I am providing you optional feedback Kindly implement it: When you `pressed`  your button and when you `Enabled` your button it is working fine but when the user ` Hover` the button then your design is not like Figma. so see this image below
### Your button when hover

![your hover](https://user-images.githubusercontent.com/81727988/164910113-8f7a90c5-fe5d-46be-8fa1-6c854bba2e77.png)

### Figma design
![Figma](https://user-images.githubusercontent.com/81727988/164910124-35044aea-5b9e-4849-afbb-4e15d52b0057.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-04-23 15:27 UTC, merged